spring:
  profiles:
    active: dev


  datasource:
    url: your_address
    username: user
    password: password

bot:
  botName: botName
  botToken: botToken

weather:
  key: apiKey
  url: apiURL

currency:
  key: apiKey
  url: apiURL
