spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bot:
  botName: ${BOT_NAME}
  botToken: ${BOT_TOKEN}

weather:
  key: ${WEATHER_KEY}
  url: ${WEATHER_URL}

currency:
  key: ${CURRENCY_KEY}
  url: ${CURRENCY_URL}
